CREATE SCHEMA IF NOT EXISTS customer;
CREATE SCHEMA IF NOT EXISTS catalog;
CREATE SCHEMA IF NOT EXISTS cart;
CREATE SCHEMA IF NOT EXISTS ordering;
CREATE SCHEMA IF NOT EXISTS favorite;
CREATE SCHEMA IF NOT EXISTS promotion;

ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS old_price DOUBLE PRECISION DEFAULT 0;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS discount_rate INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS rating DOUBLE PRECISION DEFAULT 0;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS review_count INTEGER DEFAULT 0;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS color VARCHAR(64);
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS size VARCHAR(16);
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS free_cargo BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS seller_score DOUBLE PRECISION DEFAULT 0;
ALTER TABLE IF EXISTS catalog.products ADD COLUMN IF NOT EXISTS installment_text VARCHAR(64);

ALTER TABLE IF EXISTS promotion.promotion_banners ADD COLUMN IF NOT EXISTS description VARCHAR(500);
ALTER TABLE IF EXISTS promotion.promotion_banners ADD COLUMN IF NOT EXISTS block_type VARCHAR(32);
ALTER TABLE IF EXISTS promotion.promotion_banners ADD COLUMN IF NOT EXISTS sort_order INTEGER;
