spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/trend-burada
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: platform-auth
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: platform-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**,/api/home/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userOrIpKeyResolver}"
            - name: Retry
              args:
                retries: 2
                methods: GET,POST
                statuses: BAD_GATEWAY,GATEWAY_TIMEOUT,SERVICE_UNAVAILABLE
            - name: CircuitBreaker
              args:
                name: platformCircuitBreaker
                fallbackUri: forward:/fallback/platform
        - id: actuator-health
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**

resilience4j:
  circuitbreaker:
    instances:
      platformCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
