spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trend_burada_app
    username: trend
    password: trend
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  auth:
    keycloak:
      base-url: http://localhost:8081
      admin-username: admin
      admin-password: admin
      client-secret:
